### ISSUE TITLE
希望在 yaml 代码中添加更多信息

### ISSUE THREAD

**Issue by Mrered** [halo-sigs/vscode-extension-halo#3]
希望可以在 yaml 配置信息中添加：

- 分类
- 标签
- 文章头部图片
- 主题中包含的元数据
- 其他自定义元数据

**Comment by ruibaby** [comment]
分类和标签等通用的配置我将放置在 halo 对象外，以尝试兼容其他平台的 Markdown 文件。如：

```
---
title: "Halo"
categories: []
tags: []
halo:
  site: https://ryanc.cc
  name: "test"
  publish: true
---
```
